language: python
cache: pip
matrix:
  include:
    - python: 3.8
      arch: amd64
    - arch: arm64
      python: 3.8
      virt: lxd
      dist: xenial
      group: edge
    - arch: arm64-graviton2
      python: 3.8
      virt: lxd
      dist: xenial
      group: edge
    - arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - arch: arm64-graviton2
      python: 3.7
      virt: lxd
      dist: xenial
      group: edge

install:
  - "pip install mock"
script: "python -m unittest discover -p *_test.py"
